"""Display names for the 120 outlets and the 60 vehicles' drivers (all fictional)."""

OUTLET_NAMES = {
    1: "Borella",
    2: "Maradana",
    3: "Kotahena",
    4: "Bambalapitiya",
    5: "Wellawatte",
    6: "Grandpass",
    7: "Dehiwala",
    8: "Narahenpita",
    9: "Nugegoda",
    10: "Maharagama",
    11: "Kirulapone",
    12: "Battaramulla",
    13: "Rajagiriya",
    14: "Kohuwala",
    15: "Lotus Arcade Style",
    16: "Harbour Mall Style",
    17: "Parkside Mall Style",
    18: "Crescent Mall Style",
    19: "Bambalapitiya Style",
    20: "Pettah Style",
    21: "Parkside Mall Tech",
    22: "Colombo City Mall",
    23: "Kollupitiya",
    24: "Havelock",
    25: "Ragama",
    26: "Kelaniya",
    27: "Kiribathgoda",
    28: "Kadawatha",
    29: "Ja-Ela",
    30: "Wattala",
    31: "Kandana",
    32: "Negombo",
    33: "Minuwangoda",
    34: "Gampaha Town",
    35: "Kelani Mall Style",
    36: "Lagoon Mall Style",
    37: "Gampaha Style",
    38: "Kadawatha Tech",
    39: "Gampaha Tech",
    40: "Wadduwa",
    41: "Horana",
    42: "Panadura",
    43: "Bandaragama",
    44: "Kalutara Town",
    45: "Aluthgama",
    46: "Beruwala",
    47: "Panadura Style",
    48: "Kalutara Style",
    49: "Horana Tech",
    50: "Ambalangoda",
    51: "Karapitiya",
    52: "Unawatuna",
    53: "Galle Fort",
    54: "Hikkaduwa",
    55: "Baddegama",
    56: "Galle Bay Mall",
    57: "Galle Town",
    58: "Galle Tech",
    59: "Akuressa",
    60: "Matara Town",
    61: "Kamburugamuwa",
    62: "Weligama",
    63: "Matara Style",
    64: "Matara Tech",
    65: "Kurunegala Town",
    66: "Kuliyapitiya",
    67: "Wariyapola",
    68: "Pannala",
    69: "Narammala",
    70: "Kurunegala Style",
    71: "Kurunegala Arcade",
    72: "Kurunegala Tech",
    73: "Chilaw",
    74: "Puttalam Town",
    75: "Marawila",
    76: "Ampitiya",
    77: "Peradeniya",
    78: "Katugastota",
    79: "Kandy Town",
    80: "Kundasale",
    81: "Gampola",
    82: "Pilimathalawa",
    83: "Akurana",
    84: "Kadugannawa",
    85: "Digana",
    86: "Nawalapitiya",
    87: "Galagedara",
    88: "Peradeniya Road Style",
    89: "Kandy City Mall",
    90: "Lakeview Arcade Style",
    91: "Katugastota Style",
    92: "Kandy Town Style",
    93: "Kandy Market Tech",
    94: "Kandy City Mall Tech",
    95: "Kandy Tech",
    96: "Rattota",
    97: "Galewela",
    98: "Naula",
    99: "Ukuwela",
    100: "Matale Town",
    101: "Dambulla",
    102: "Matale Style",
    103: "Dambulla Tech",
    104: "Pussellawa",
    105: "Nuwara Eliya Town",
    106: "Ramboda",
    107: "Nanu Oya",
    108: "Hawa Eliya",
    109: "Nuwara Eliya Style",
    110: "Hali-Ela",
    111: "Welimada",
    112: "Badulla Town",
    113: "Bandarawela",
    114: "Bandarawela Style",
    115: "Badulla Tech",
    116: "Rambukkana",
    117: "Kegalle Town",
    118: "Mawanella",
    119: "Warakapola",
    120: "Kegalle Style",
}

STORE_MANAGERS = {105: "Fathima Rizwan"}
_FIRST = [
    "Nadeesha",
    "Ruwani",
    "Tharaka",
    "Dilini",
    "Imesha",
    "Kavindi",
    "Sanduni",
    "Anjali",
    "Hasini",
    "Pavithra",
    "Mohamed",
    "Chamari",
    "Ishani",
    "Nilmini",
    "Shalini",
    "Gayathri",
    "Rizana",
    "Priyanka",
    "Malsha",
    "Udari",
]


def manager_for(n: int) -> str:
    if n in STORE_MANAGERS:
        return STORE_MANAGERS[n]
    return _FIRST[n % len(_FIRST)]


DRIVERS = [
    "Chaminda Silva",
    "Ruwan Perera",
    "Nimal Fernando",
    "Ashan Kumara",
    "Pradeep Wijesinghe",
    "Mahesh Dias",
    "Kamal Jayasuriya",
    "Dilan Rodrigo",
    "Tharindu Mendis",
    "Ishara Nanayakkara",
    "Sampath Gunawardena",
    "Lakmal Rajapaksha",
    "Nuwan Priyankara",
    "Saman Kulatunga",
    "Janaka Weerasinghe",
    "Upul Samarasinghe",
    "Asanka Herath",
    "Kasun Madushanka",
    "Roshan Fonseka",
    "Chathura Jayawardena",
    "Dinuka Abeysekara",
    "Isuru Karunaratne",
    "Harsha De Mel",
    "Malith Ekanayake",
    "Supun Wickramasinghe",
    "Gihan Liyanage",
    "Mohamed Rizwan",
    "Fazil Hameed",
    "Ravi Shanmugam",
    "Suresh Kumar",
    "Anura Bandara",
    "Sanjeewa Lokuge",
    "Roshan Bandara",
    "Gayan Tennakoon",
    "Lahiru Senanayake",
    "Priyantha Aluthge",
    "Nuwan Herath",
    "Thilina Dissanayake",
    "Mahinda Ratnayake",
    "Buddhika Wijeratne",
    "Chamara Kodithuwakku",
    "Nalin Jayasinghe",
    "Viraj Amarasinghe",
    "Sathis Rajendran",
    "Kavinda Pathirana",
    "Ajith Munasinghe",
    "Rukshan Perera",
    "Dhammika Senaratne",
    "Wasantha Gamage",
    "Prasad Wanigasekara",
    "Lalith Somaratne",
    "Janith Ranasinghe",
    "Shehan Mendis",
    "Arjun Selvarajah",
    "Chandana Premadasa",
    "Duminda Hettiarachchi",
    "Kelum Weerakoon",
    "Sisira Kumara",
    "Rohan Jayakody",
    "Sunil Rathnayake",
]

# the people the walkthrough meets
DRIVER_FOR = {"VEH057": "Sunil Rathnayake", "VEH042": "Roshan Bandara", "VEH058": "Shehan Mendis"}


def driver_for(vehicle_id: str) -> str:
    if vehicle_id in DRIVER_FOR:
        return DRIVER_FOR[vehicle_id]
    n = int(vehicle_id[3:])
    pool = [d for d in DRIVERS if d not in DRIVER_FOR.values()]
    return pool[(n - 1) % len(pool)]
