"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-01 12:42:47.177452
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("short_name", sa.String(length=40), nullable=False),
        sa.Column("initials", sa.String(length=4), nullable=False),
        sa.Column("color", sa.String(length=16), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("depot", sa.String(length=20), nullable=True),
        sa.Column("dock", sa.Integer(), nullable=True),
        sa.Column("vehicle_id", sa.String(length=10), nullable=True),
        sa.Column("outlet_id", sa.String(length=10), nullable=True),
        sa.Column("lang", sa.String(length=4), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "calendar_day",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("dow", sa.Integer(), nullable=False),
        sa.Column("is_payday", sa.Boolean(), nullable=False),
        sa.Column("festival", sa.String(length=30), nullable=True),
        sa.Column("festival_ramp", sa.Float(), nullable=False),
        sa.Column("is_holiday", sa.Boolean(), nullable=False),
        sa.Column("monsoon", sa.Boolean(), nullable=False),
        sa.Column("is_operating", sa.Boolean(), nullable=False),
        sa.Column("iso_year", sa.Integer(), nullable=False),
        sa.Column("iso_week", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("date"),
    )
    op.create_table(
        "depot",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("code", sa.String(length=4), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("docks", sa.Integer(), nullable=False),
        sa.Column("bays_per_dock", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product",
        sa.Column("sku", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("brand", sa.String(length=10), nullable=False),
        sa.Column("temp", sa.String(length=8), nullable=False),
        sa.Column("unit_kg", sa.Float(), nullable=False),
        sa.Column("unit_m3", sa.Float(), nullable=False),
        sa.Column("uom", sa.String(length=12), nullable=False),
        sa.Column("share", sa.Float(), nullable=False),
        sa.Column("sort", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("sku"),
    )
    op.create_table(
        "service_allowance",
        sa.Column("brand", sa.String(length=10), nullable=False),
        sa.Column("dock_type", sa.String(length=12), nullable=False),
        sa.Column("minutes", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("brand", "dock_type"),
    )
    op.create_table(
        "traffic_speed",
        sa.Column("district", sa.String(length=30), nullable=False),
        sa.Column("hour", sa.Integer(), nullable=False),
        sa.Column("monsoon", sa.Integer(), nullable=False),
        sa.Column("speed_index", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("district", "hour", "monsoon"),
    )
    op.create_table(
        "workspace",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("clock_anchor_real", sa.DateTime(timezone=True), nullable=False),
        sa.Column("clock_anchor_virtual", sa.DateTime(), nullable=False),
        sa.Column("clock_rate", sa.Float(), nullable=False),
        sa.Column("clock_paused", sa.Boolean(), nullable=False),
        sa.Column("service_date", sa.Date(), nullable=False),
        sa.Column("orders_closed_at", sa.DateTime(), nullable=True),
        sa.Column("seed_version", sa.Integer(), nullable=False),
        sa.Column("sandbox", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "device_seen",
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("last_seen_real", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_virtual", sa.DateTime(), nullable=True),
        sa.Column("pending", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("workspace_id", "user_id"),
    )
    op.create_table(
        "district",
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("depot", sa.String(length=20), nullable=False),
        sa.Column("road_class", sa.String(length=20), nullable=False),
        sa.Column("free_flow_kmh", sa.Float(), nullable=False),
        sa.Column("d2d_km", sa.Float(), nullable=False),
        sa.Column("d2d_min", sa.Integer(), nullable=False),
        sa.Column("inter_km", sa.Float(), nullable=False),
        sa.Column("inter_min", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["depot"],
            ["depot.id"],
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "event",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("type", sa.String(length=40), nullable=False),
        sa.Column("actor_name", sa.String(length=60), nullable=False),
        sa.Column("actor_role", sa.String(length=16), nullable=False),
        sa.Column("entity", sa.String(length=40), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("virtual_at", sa.DateTime(), nullable=False),
        sa.Column("device_at", sa.DateTime(), nullable=True),
        sa.Column("server_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("client_event_id", sa.String(length=64), nullable=True),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "client_event_id", name="uq_event_client_id"),
    )
    op.create_index(op.f("ix_event_workspace_id"), "event", ["workspace_id"], unique=False)
    op.create_index("ix_event_ws_id", "event", ["workspace_id", "id"], unique=False)
    op.create_table(
        "media",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("content_type", sa.String(length=40), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_media_workspace_id"), "media", ["workspace_id"], unique=False)
    op.create_table(
        "notice",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("audience", sa.String(length=30), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("icon", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=140), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("at", sa.DateTime(), nullable=False),
        sa.Column("actions", sa.JSON(), nullable=False),
        sa.Column("key", sa.String(length=60), nullable=True),
        sa.Column("entity", sa.String(length=40), nullable=True),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notice_audience"), "notice", ["audience"], unique=False)
    op.create_index(op.f("ix_notice_workspace_id"), "notice", ["workspace_id"], unique=False)
    op.create_index("ix_notice_ws_aud", "notice", ["workspace_id", "audience", "resolved"], unique=False)
    op.create_table(
        "plan",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("service_date", sa.Date(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("policy", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=60), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("solver", sa.JSON(), nullable=False),
        sa.Column("kpis", sa.JSON(), nullable=False),
        sa.Column("lever_cache", sa.JSON(), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plan_workspace_id"), "plan", ["workspace_id"], unique=False)
    op.create_table(
        "vehicle",
        sa.Column("id", sa.String(length=10), nullable=False),
        sa.Column("type", sa.String(length=8), nullable=False),
        sa.Column("temp", sa.String(length=8), nullable=False),
        sa.Column("weight_cap_kg", sa.Float(), nullable=False),
        sa.Column("volume_cap_m3", sa.Float(), nullable=False),
        sa.Column("fuel_type", sa.String(length=10), nullable=False),
        sa.Column("km_per_l", sa.Float(), nullable=False),
        sa.Column("weekly_fuel_quota_l", sa.Float(), nullable=False),
        sa.Column("depot", sa.String(length=20), nullable=False),
        sa.Column("driver_name", sa.String(length=60), nullable=False),
        sa.ForeignKeyConstraint(
            ["depot"],
            ["depot.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "outlet",
        sa.Column("id", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("brand", sa.String(length=10), nullable=False),
        sa.Column("district", sa.String(length=30), nullable=False),
        sa.Column("depot", sa.String(length=20), nullable=False),
        sa.Column("dock_type", sa.String(length=12), nullable=False),
        sa.Column("parking", sa.String(length=12), nullable=False),
        sa.Column("mall_window", sa.String(length=12), nullable=True),
        sa.Column("window_open", sa.String(length=5), nullable=False),
        sa.Column("window_close", sa.String(length=5), nullable=False),
        sa.Column("usual_vehicle_ambient", sa.String(length=10), nullable=True),
        sa.Column("usual_vehicle_chilled", sa.String(length=10), nullable=True),
        sa.Column("manager", sa.String(length=60), nullable=False),
        sa.ForeignKeyConstraint(
            ["depot"],
            ["depot.id"],
        ),
        sa.ForeignKeyConstraint(
            ["district"],
            ["district.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trip",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("service_date", sa.Date(), nullable=False),
        sa.Column("code", sa.String(length=8), nullable=False),
        sa.Column("vehicle_id", sa.String(length=10), nullable=False),
        sa.Column("trip_no", sa.Integer(), nullable=False),
        sa.Column("depot", sa.String(length=20), nullable=False),
        sa.Column("brand", sa.String(length=10), nullable=False),
        sa.Column("district", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("planned_depart", sa.DateTime(), nullable=False),
        sa.Column("planned_return", sa.DateTime(), nullable=True),
        sa.Column("minutes", sa.Integer(), nullable=False),
        sa.Column("km", sa.Float(), nullable=False),
        sa.Column("litres", sa.Float(), nullable=False),
        sa.Column("volume_m3", sa.Float(), nullable=False),
        sa.Column("weight_kg", sa.Float(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("dock", sa.Integer(), nullable=False),
        sa.Column("bay", sa.Integer(), nullable=False),
        sa.Column("controlled", sa.String(length=6), nullable=False),
        sa.Column("loading_started_at", sa.DateTime(), nullable=True),
        sa.Column("released_at", sa.DateTime(), nullable=True),
        sa.Column("released_by", sa.String(length=60), nullable=True),
        sa.Column("release_temp_c", sa.Float(), nullable=True),
        sa.Column("seal_no", sa.String(length=20), nullable=True),
        sa.Column("doors_ok", sa.Boolean(), nullable=True),
        sa.Column("departed_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("last_contact_at", sa.DateTime(), nullable=True),
        sa.Column("signal", sa.String(length=6), nullable=False),
        sa.Column("dark_since", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["plan_id"], ["plan.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicle.id"],
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trip_plan_id"), "trip", ["plan_id"], unique=False)
    op.create_index(op.f("ix_trip_workspace_id"), "trip", ["workspace_id"], unique=False)
    op.create_index("ix_trip_ws_date", "trip", ["workspace_id", "service_date"], unique=False)
    op.create_table(
        "vehicle_day",
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("vehicle_id", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("fuel_used_l", sa.Float(), nullable=False),
        sa.Column("back_on", sa.Date(), nullable=True),
        sa.Column("note", sa.String(length=120), nullable=False),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicle.id"],
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("workspace_id", "date", "vehicle_id"),
    )
    op.create_table(
        "order_",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("ref", sa.String(length=16), nullable=False),
        sa.Column("outlet_id", sa.String(length=10), nullable=False),
        sa.Column("service_date", sa.Date(), nullable=False),
        sa.Column("brand", sa.String(length=10), nullable=False),
        sa.Column("temp", sa.String(length=8), nullable=False),
        sa.Column("units", sa.Integer(), nullable=False),
        sa.Column("weight_kg", sa.Float(), nullable=False),
        sa.Column("volume_m3", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("channel", sa.String(length=12), nullable=False),
        sa.Column("placed_at", sa.DateTime(), nullable=False),
        sa.Column("placed_by", sa.Integer(), nullable=True),
        sa.Column("deferred_yesterday", sa.Boolean(), nullable=False),
        sa.Column("days_since_served", sa.Integer(), nullable=False),
        sa.Column("deferral_streak", sa.Integer(), nullable=False),
        sa.Column("origin_order_id", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(length=160), nullable=False),
        sa.ForeignKeyConstraint(
            ["origin_order_id"],
            ["order_.id"],
        ),
        sa.ForeignKeyConstraint(
            ["outlet_id"],
            ["outlet.id"],
        ),
        sa.ForeignKeyConstraint(
            ["placed_by"],
            ["app_user.id"],
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "ref"),
    )
    op.create_index(op.f("ix_order__workspace_id"), "order_", ["workspace_id"], unique=False)
    op.create_index("ix_order_ws_date", "order_", ["workspace_id", "service_date"], unique=False)
    op.create_index("ix_order_ws_outlet", "order_", ["workspace_id", "outlet_id"], unique=False)
    op.create_table(
        "standing_order",
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("outlet_id", sa.String(length=10), nullable=False),
        sa.Column("temp", sa.String(length=8), nullable=False),
        sa.Column("lines", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["outlet_id"],
            ["outlet.id"],
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("workspace_id", "outlet_id", "temp"),
    )
    op.create_table(
        "deferral",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=True),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=12), nullable=False),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("cost", sa.JSON(), nullable=False),
        sa.Column("streak", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("decided_by", sa.String(length=60), nullable=False),
        sa.Column("next_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(["order_id"], ["order_.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["plan_id"], ["plan.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_deferral_order_id"), "deferral", ["order_id"], unique=False)
    op.create_index(op.f("ix_deferral_workspace_id"), "deferral", ["workspace_id"], unique=False)
    op.create_table(
        "order_line",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("sku", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("uom", sa.String(length=12), nullable=False),
        sa.Column("load_state", sa.String(length=10), nullable=False),
        sa.Column("loaded_qty", sa.Integer(), nullable=True),
        sa.Column("loaded_by", sa.String(length=60), nullable=True),
        sa.Column("loaded_at", sa.DateTime(), nullable=True),
        sa.Column("delivered_qty", sa.Integer(), nullable=True),
        sa.Column("received_qty", sa.Integer(), nullable=True),
        sa.Column("receipt_issue", sa.String(length=16), nullable=True),
        sa.Column("receipt_note", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(["order_id"], ["order_.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["sku"],
            ["product.sku"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_order_line_order_id"), "order_line", ["order_id"], unique=False)
    op.create_table(
        "pending_move",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("from_trip_id", sa.Integer(), nullable=False),
        sa.Column("to_vehicle_id", sa.String(length=10), nullable=False),
        sa.Column("to_trip_no", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("created_by", sa.String(length=60), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("resolution", sa.String(length=300), nullable=False),
        sa.ForeignKeyConstraint(["from_trip_id"], ["trip.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["order_id"], ["order_.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pending_move_workspace_id"), "pending_move", ["workspace_id"], unique=False)
    op.create_table(
        "receipt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("by_name", sa.String(length=60), nullable=False),
        sa.Column("at", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("note", sa.String(length=300), nullable=False),
        sa.Column("simulated", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["order_.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id"),
    )
    op.create_index(op.f("ix_receipt_workspace_id"), "receipt", ["workspace_id"], unique=False)
    op.create_table(
        "stop",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("planned_arrival", sa.DateTime(), nullable=False),
        sa.Column("planned_start", sa.DateTime(), nullable=False),
        sa.Column("planned_finish", sa.DateTime(), nullable=False),
        sa.Column("late_planned", sa.Boolean(), nullable=False),
        sa.Column("pred_service_min", sa.Float(), nullable=False),
        sa.Column("late_prob", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("arrived_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recorded_offline", sa.Boolean(), nullable=False),
        sa.Column("outcome_note", sa.String(length=200), nullable=False),
        sa.Column("simulated", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["order_.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["trip_id"], ["trip.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stop_order_id"), "stop", ["order_id"], unique=False)
    op.create_index(op.f("ix_stop_trip_id"), "stop", ["trip_id"], unique=False)
    op.create_index(op.f("ix_stop_workspace_id"), "stop", ["workspace_id"], unique=False)
    op.create_table(
        "issue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=True),
        sa.Column("stop_id", sa.Integer(), nullable=True),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("line_id", sa.Integer(), nullable=True),
        sa.Column("qty", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(length=300), nullable=False),
        sa.Column("raised_by", sa.String(length=60), nullable=False),
        sa.Column("raised_role", sa.String(length=16), nullable=False),
        sa.Column("raised_at", sa.DateTime(), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=True),
        sa.Column("decision_text", sa.String(length=300), nullable=True),
        sa.Column("decided_by", sa.String(length=60), nullable=True),
        sa.Column("decided_at", sa.DateTime(), nullable=True),
        sa.Column("acked_at", sa.DateTime(), nullable=True),
        sa.Column("photo_media_id", sa.String(length=36), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["line_id"], ["order_line.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["order_id"], ["order_.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["stop_id"], ["stop.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["trip_id"], ["trip.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_issue_workspace_id"), "issue", ["workspace_id"], unique=False)
    op.create_table(
        "proof",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("stop_id", sa.Integer(), nullable=False),
        sa.Column("receiver_name", sa.String(length=60), nullable=False),
        sa.Column("photo_media_id", sa.String(length=36), nullable=True),
        sa.Column("signature_media_id", sa.String(length=36), nullable=True),
        sa.Column("note", sa.String(length=200), nullable=False),
        sa.Column("captured_at", sa.DateTime(), nullable=False),
        sa.Column("simulated", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["stop_id"], ["stop.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_proof_stop_id"), "proof", ["stop_id"], unique=False)
    op.create_index(op.f("ix_proof_workspace_id"), "proof", ["workspace_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_proof_workspace_id"), table_name="proof")
    op.drop_index(op.f("ix_proof_stop_id"), table_name="proof")
    op.drop_table("proof")
    op.drop_index(op.f("ix_issue_workspace_id"), table_name="issue")
    op.drop_table("issue")
    op.drop_index(op.f("ix_stop_workspace_id"), table_name="stop")
    op.drop_index(op.f("ix_stop_trip_id"), table_name="stop")
    op.drop_index(op.f("ix_stop_order_id"), table_name="stop")
    op.drop_table("stop")
    op.drop_index(op.f("ix_receipt_workspace_id"), table_name="receipt")
    op.drop_table("receipt")
    op.drop_index(op.f("ix_pending_move_workspace_id"), table_name="pending_move")
    op.drop_table("pending_move")
    op.drop_index(op.f("ix_order_line_order_id"), table_name="order_line")
    op.drop_table("order_line")
    op.drop_index(op.f("ix_deferral_workspace_id"), table_name="deferral")
    op.drop_index(op.f("ix_deferral_order_id"), table_name="deferral")
    op.drop_table("deferral")
    op.drop_table("standing_order")
    op.drop_index("ix_order_ws_outlet", table_name="order_")
    op.drop_index("ix_order_ws_date", table_name="order_")
    op.drop_index(op.f("ix_order__workspace_id"), table_name="order_")
    op.drop_table("order_")
    op.drop_table("vehicle_day")
    op.drop_index("ix_trip_ws_date", table_name="trip")
    op.drop_index(op.f("ix_trip_workspace_id"), table_name="trip")
    op.drop_index(op.f("ix_trip_plan_id"), table_name="trip")
    op.drop_table("trip")
    op.drop_table("outlet")
    op.drop_table("vehicle")
    op.drop_index(op.f("ix_plan_workspace_id"), table_name="plan")
    op.drop_table("plan")
    op.drop_index("ix_notice_ws_aud", table_name="notice")
    op.drop_index(op.f("ix_notice_workspace_id"), table_name="notice")
    op.drop_index(op.f("ix_notice_audience"), table_name="notice")
    op.drop_table("notice")
    op.drop_index(op.f("ix_media_workspace_id"), table_name="media")
    op.drop_table("media")
    op.drop_index("ix_event_ws_id", table_name="event")
    op.drop_index(op.f("ix_event_workspace_id"), table_name="event")
    op.drop_table("event")
    op.drop_table("district")
    op.drop_table("device_seen")
    op.drop_table("workspace")
    op.drop_table("traffic_speed")
    op.drop_table("service_allowance")
    op.drop_table("product")
    op.drop_table("depot")
    op.drop_table("calendar_day")
    op.drop_table("app_user")
    # ### end Alembic commands ###
